version: "3"
services: 
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"        
    env_file:
      - 'influxdb.env'
    volumes:
      - "influxdb-data:/var/lib/influxdb"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    user: "0"
    volumes:
      - "grafana-data:/var/lib/grafana"
  
  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - "node-red-data:/data"
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto"

volumes:
  influxdb-data:
  grafana-data:        
  node-red-data:
  mosquitto-data:


