services: 
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"        
    env_file:
      - 'influxdb.env'
    volumes:
      - "influxdb-data:/var/lib/influxdb"

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=oee
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=S3cret@1234
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin_user@domain.com
      PGADMIN_DEFAULT_PASSWORD: S3cret@1234
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    user: "0"
    volumes:
      - "grafana-data:/var/lib/grafana"
  
  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - "node-red-data:/data"
  
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "mosquitto-data:/mosquitto"

volumes:
  influxdb-data:
  postgres-data:
  pgadmin-data:
  grafana-data:        
  node-red-data:
  mosquitto-data:


